// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayroolAPI.Models;

namespace PayroolAPI.Migrations
{
    [DbContext(typeof(payrollContext))]
    partial class payrollContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PayroolAPI.Models.DboEmpInfo", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpAllakab");

                    b.Property<DateTime?>("EmpApOrDt");

                    b.Property<string>("EmpApOrNo");

                    b.Property<string>("EmpAppoSt");

                    b.Property<string>("EmpAsgStu");

                    b.Property<string>("EmpBirthCou");

                    b.Property<string>("EmpBirthGov");

                    b.Property<string>("EmpBocCo");

                    b.Property<string>("EmpCecMomNam");

                    b.Property<DateTime?>("EmpDateofbirth");

                    b.Property<string>("EmpDngHotPlc");

                    b.Property<string>("EmpEmail");

                    b.Property<string>("EmpEmployer");

                    b.Property<string>("EmpEmployerTyp");

                    b.Property<string>("EmpFirMomNam");

                    b.Property<string>("EmpFirNam");

                    b.Property<string>("EmpForthNam");

                    b.Property<string>("EmpFullName");

                    b.Property<string>("EmpGender");

                    b.Property<string>("EmpHealthNo");

                    b.Property<bool?>("EmpHelthInsEmp");

                    b.Property<string>("EmpIdNo");

                    b.Property<string>("EmpItem");

                    b.Property<DateTime?>("EmpLstUpdDt");

                    b.Property<int?>("EmpLthServMonth");

                    b.Property<int?>("EmpLthServYear");

                    b.Property<string>("EmpMarStu");

                    b.Property<bool?>("EmpMedicalBen");

                    b.Property<string>("EmpMinCo");

                    b.Property<string>("EmpMomNam");

                    b.Property<DateTime?>("EmpNaDt");

                    b.Property<string>("EmpNaNo");

                    b.Property<string>("EmpNatIssProv");

                    b.Property<string>("EmpNati");

                    b.Property<string>("EmpNo");

                    b.Property<string>("EmpNumDyMrt");

                    b.Property<string>("EmpPepGrp");

                    b.Property<string>("EmpPerTyp");

                    b.Property<string>("EmpPhonNo");

                    b.Property<bool?>("EmpRadiBen");

                    b.Property<string>("EmpReligion");

                    b.Property<string>("EmpRetNo");

                    b.Property<bool?>("EmpSalRec");

                    b.Property<string>("EmpSecNam");

                    b.Property<string>("EmpServAd");

                    b.Property<int?>("EmpServAdMonth");

                    b.Property<int?>("EmpServAdYear");

                    b.Property<int?>("EmpServOutSalryMm");

                    b.Property<int?>("EmpServOutSalryYy");

                    b.Property<bool?>("EmpStaff");

                    b.Property<bool?>("EmpStaffRes");

                    b.Property<DateTime?>("EmpStartDt");

                    b.Property<string>("EmpStatNo");

                    b.Property<string>("EmpSubUntGov");

                    b.Property<string>("EmpSubUntNo");

                    b.Property<string>("EmpSupplyCardNo");

                    b.Property<string>("EmpTherMomNam");

                    b.Property<string>("EmpTherNam");

                    b.Property<string>("EmpUnCo");

                    b.Property<string>("EmpUpgrTb");

                    b.Property<string>("EmpUpgrYe");

                    b.Property<string>("EmpVoterno");

                    b.Property<string>("EmpWorSt");

                    b.Property<string>("EmpstdNo");

                    b.HasKey("EmpId");

                    b.ToTable("DboEmpInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
